### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by K1ZANA** [KadeDev/Kade-Engine#2145]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Linux

## What version of the game are you using? Look in the bottom left corner of the main menu.

Latest

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Trying to build the engine on Linux

## Please describe your issue. Provide extensive detail and images if possible.

I only did lime build linux, after that it terminated with the error:
```yml
Error: In file included from ./src/LuaCharacter.cpp:6:
/home/kizana/haxelib/linc_luajit/git//linc/linc_lua.h:10:10: fatal error: ../lib/lua/src/lua.hpp: Datei oder Verzeichnis nicht gefunden
   10 | #include "../lib/lua/src/lua.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Reycko** [comment]
looks like C, and i'm not that good + I am a Windows user
Sorry i can't help you.

**Comment by Dobby233Liu** [comment]
Duplicate of #2074
