### ISSUE TITLE
 add the icons

### ISSUE THREAD

**Issue by jefer368** [KadeDev/Kade-Engine#2155]
Well, I honestly do not know how to add icons because I change the names and the way to add them and because someone knows how to add the icons?

**Comment by Ninjakaiden523** [comment]
go to assets/preload/images/icons go to a random icon copy it out of the folder remove the icons in the image and past your icon over where the other icons were. **normal is left losing is right**.

**Comment by Ninjakaiden523** [comment]
my character's icon for example 
![icon-anon](https://user-images.githubusercontent.com/77185327/132139938-134ff146-6201-4c02-8541-b63ad27f5f16.png)
