### ISSUE TITLE
add icons

### ISSUE THREAD

**Issue by jefer368** [KadeDev/Kade-Engine#2202]
I am somewhat lost in adding the icons, does anyone know how?

**Comment by napstaa967** [comment]
1.6.2+: make a new file called "icon-<character name>.png" that is 300x150 in size and add the icons to it, then leave it on the icons folder
if the name has a "-" modify healthicon.hx and add
```hx
if (char != 'bf-pixel' && char != 'bf-old' && char != 'your character name with the dash')
			char = char.split("-")[0];
```
then change the file name
