### ISSUE TITLE
Bug Report: can't find a way to compile the game my self

### ISSUE THREAD

**Issue by sebby09559** [KadeDev/Kade-Engine#371]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by prokube** [comment]
literally BUILDING.md

we officially support macos now too

**Comment by KadeDev** [comment]
you gave us absolutely no information, also this is a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)
